# Generated by Django 4.2.20 on 2025-07-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="app_name",
            field=models.CharField(default="default", max_length=255),
        ),
    ]
