# Generated by Django 4.2.27 on 2026-01-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("simple_notifications", "0002_pushsubscription_app_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pushsubscription",
            old_name="user",
            new_name="original_user",
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="content_type",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype", null=True, blank=True),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="object_id",
            field=models.PositiveIntegerField(default=None, null=True, blank=True),
        ),
    ]
