# Generated by Django 4.2.27 on 2026-01-11 16:15

from django.db import models
from django.db import migrations
from django.contrib.auth import get_user_model


def migrate_user_to_generic_user(apps, schema_editor):
    PushSubscription = apps.get_model("simple_notifications", "PushSubscription")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type = ContentType.objects.get_for_model(get_user_model())

    for subscription in PushSubscription.objects.all():
        subscription.object_id = subscription.original_user.id
        subscription.content_type = content_type
        subscription.save()


def reverse_migrate_user_to_generic_user(apps, schema_editor):
    PushSubscription = apps.get_model("simple_notifications", "PushSubscription")
    for subscription in PushSubscription.objects.all():
        subscription.original_user = subscription.object_id
        subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ("simple_notifications", "0003_pushsubscription_generic_key"),
    ]

    operations = [
        migrations.RunPython(
            migrate_user_to_generic_user,
            reverse_migrate_user_to_generic_user,
        ),
        migrations.RemoveField(
            model_name="pushsubscription",
            name="original_user",
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="content_type",
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
