# Generated by Django 4.2.27 on 2026-01-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_notifications", "0004_datamigration_generic_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pushsubscription",
            name="original_user",
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="content_type",
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
